version: "3.8"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: tools/Dockerfile
      args:
        APP_DIR: /var/www/app
        PROCUSER: www-data
        PROCUID: $APP_PROCUID
        PROCGID: $APP_PROCGID
    platform: ${DOCKER_PLATFORM}
    tty: true
    volumes:
      - .app/:/var/www/app
    networks:
      - site_compare
networks:
  site_compare:
    driver: bridge